# Generated by Django 3.2.9 on 2023-10-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNIC', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=255)),
                ('Father_Husband_Name', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=100)),
                ('License_Number', models.CharField(max_length=20)),
                ('Issue_Date', models.DateField()),
                ('Valid_From', models.DateField()),
                ('Valid_To', models.DateField()),
                ('Allowed_Vehicles', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
    ]
