# Generated by Django 3.2.9 on 2023-10-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifyLic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
