# Generated by Django 3.2.9 on 2023-10-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifyLic', '0002_alter_license_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_holder_image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
