# Generated by Django 3.2.9 on 2023-10-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifyLic', '0003_license_license_holder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_holder_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
