# Generated by Django 3.2.9 on 2023-10-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifyLic', '0004_alter_license_license_holder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='License_Number',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='license',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Canceled', 'Canceled'), ('Under Processing', 'Under Processing')], default='pending', max_length=20),
        ),
    ]
