# Generated by Django 3.2.9 on 2023-10-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifyLic', '0005_auto_20231025_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_holder_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
