# Generated by Django 3.2.9 on 2023-10-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifyLic', '0006_alter_license_license_holder_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='license_holder_image',
        ),
    ]
