# Generated by Django 3.2.9 on 2023-10-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifyLic', '0008_license_license_holder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_holder_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
