# Generated by Django 3.2.9 on 2023-10-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifyLic', '0012_alter_license_license_holder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='CNIC',
            field=models.CharField(max_length=13),
        ),
    ]
